[package]
name = "rust-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
#rust-common = { path = "../rust-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }


[[bin]]
name = "rust"
path = "src/main.rs"
